version: "3.9"

services:
  db:
    image: postgres:16
    container_name: lego-inventory-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lego_inventory
      POSTGRES_USER: lego_user
      POSTGRES_PASSWORD: lego_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # external:internal (you can tweak if 5432 is used already)

  web:
    build:
      context: ./backend
    container_name: lego-inventory-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: lego_inventory
      POSTGRES_USER: lego_user
      POSTGRES_PASSWORD: lego_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:
